CREATE TABLE `LOG`
(  `ID` DECIMAL(19,0) NOT NULL,
   `DATE_ADDED` VARCHAR(255) NOT NULL,
   `IP_ADDRESS` VARCHAR(15),
   `USER_LOGIN` VARCHAR(255),
   `LOG_TYPE_ID` DECIMAL(19,0) NOT NULL,
  CONSTRAINT `LOG_PK` PRIMARY KEY (`ID`)
);

CREATE TABLE `LOG_CLASS`
(  `ID` DECIMAL(19,0) NOT NULL,
   `NAME` VARCHAR(255),
  CONSTRAINT `LOG_CLASS_PK` PRIMARY KEY (`ID`)
);

CREATE TABLE `LOG_DATA`
(  `ID` DECIMAL(19,0) NOT NULL,
   `NEW_VALUE` LONGTEXT,
   `OLD_VALUE` LONGTEXT,
   `VALUE` LONGTEXT,
   `LOG_ID` DECIMAL(19,0),
  CONSTRAINT `LOG_DATA_PK` PRIMARY KEY (`ID`)
);

CREATE TABLE `LOG_TYPE`
(  `ID` DECIMAL(19,0) NOT NULL,
   `NAME` VARCHAR(255),
   `LOG_CLASS_ID` DECIMAL(19,0) NOT NULL,
  CONSTRAINT `LOG_TYPE_PK` PRIMARY KEY (`ID`)
);

INSERT INTO LOG_CLASS (ID,NAME) VALUES (1,'INNER');
INSERT INTO LOG_CLASS (ID,NAME) VALUES (2,'OTHER_ITEM');

INSERT INTO LOG_TYPE (ID,NAME,LOG_CLASS_ID) VALUES (1,'NOT_SPECIFIED',1);
INSERT INTO LOG_TYPE (ID,NAME,LOG_CLASS_ID) VALUES (2,'INSERT',1);
INSERT INTO LOG_TYPE (ID,NAME,LOG_CLASS_ID) VALUES (3,'UPDATE',1);
INSERT INTO LOG_TYPE (ID,NAME,LOG_CLASS_ID) VALUES (4,'REMOVE',1);
INSERT INTO LOG_TYPE (ID,NAME,LOG_CLASS_ID) VALUES (5,'UNCAUGHT_EXCEPTION',1);
INSERT INTO LOG_TYPE (ID,NAME,LOG_CLASS_ID) VALUES (6,'CAUGHT_EXCEPTION',1);
INSERT INTO LOG_TYPE (ID,NAME,LOG_CLASS_ID) VALUES (7,'UNCAUGHT_EXCEPTION',2);